### ISSUE TITLE
compile error explanationitem does not implement interface

### ISSUE THREAD

**Issue by yuhongherald** [PowerPointLabs/PowerPointLabs#1969]
Bug introduced by #1938

**Comment by yuhongherald** [comment]
Some tests are also failing
