### PR TITLE
#1969 compile error explanationitem does not implement interface

### LINKED ISSUE #1969: compile error explanationitem does not implement interface
Bug introduced by #1938

### PR DESCRIPTION
**Pull request by yuhongherald**
Fixes #1969

### CODE REVIEW

**Comment by yuhongherald** [comment]
AgendaLab test does not pass for some reason
